/* Generated by MyraPad at 9/19/2025 8:26:02 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace DigitalRiseModel.Samples.ModelViewer.UI
{
	partial class MainPanel: Panel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Texture:";

			_textPath = new TextBox();
			_textPath.Readonly = true;
			_textPath.Width = 300;
			_textPath.Id = "_textPath";
			Grid.SetColumn(_textPath, 1);

			var label2 = new Label();
			label2.Text = "Change...";

			_buttonChangeTexture = new Button();
			_buttonChangeTexture.Id = "_buttonChangeTexture";
			Grid.SetColumn(_buttonChangeTexture, 2);
			_buttonChangeTexture.Content = label2;

			var label3 = new Label();
			label3.Text = "Clear";

			_buttonClearTexture = new Button();
			_buttonClearTexture.Id = "_buttonClearTexture";
			Grid.SetColumn(_buttonClearTexture, 3);
			_buttonClearTexture.Content = label3;

			var label4 = new Label();
			label4.Text = "Color:";
			Grid.SetRow(label4, 1);

			_imageColor = new Image();
			_imageColor.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_imageColor.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_imageColor.Id = "_imageColor";
			Grid.SetColumn(_imageColor, 1);
			Grid.SetRow(_imageColor, 1);

			var label5 = new Label();
			label5.Text = "Change...";

			_buttonChangeColor = new Button();
			_buttonChangeColor.Id = "_buttonChangeColor";
			Grid.SetColumn(_buttonChangeColor, 2);
			Grid.SetRow(_buttonChangeColor, 1);
			_buttonChangeColor.Content = label5;

			var label6 = new Label();
			label6.Text = "Clear";

			_buttonClearColor = new Button();
			_buttonClearColor.Id = "_buttonClearColor";
			Grid.SetColumn(_buttonClearColor, 3);
			Grid.SetRow(_buttonClearColor, 1);
			_buttonClearColor.Content = label6;

			var label7 = new Label();
			label7.Text = "Animation:";
			Grid.SetRow(label7, 2);

			var label8 = new Label();

			var label9 = new Label();
			label9.Text = "Move";

			var label10 = new Label();
			label10.Text = "Attack";

			_comboAnimations = new ComboView();
			_comboAnimations.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_comboAnimations.Id = "_comboAnimations";
			Grid.SetColumn(_comboAnimations, 1);
			Grid.SetRow(_comboAnimations, 2);
			_comboAnimations.Widgets.Add(label8);
			_comboAnimations.Widgets.Add(label9);
			_comboAnimations.Widgets.Add(label10);

			var label11 = new Label();
			label11.Text = "Mode:";
			Grid.SetRow(label11, 3);

			var label12 = new Label();
			label12.Text = "Forward";

			var label13 = new Label();
			label13.Text = "Backward";

			_comboPlaybackMode = new ComboView();
			_comboPlaybackMode.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_comboPlaybackMode.Id = "_comboPlaybackMode";
			Grid.SetColumn(_comboPlaybackMode, 1);
			Grid.SetRow(_comboPlaybackMode, 3);
			_comboPlaybackMode.Widgets.Add(label12);
			_comboPlaybackMode.Widgets.Add(label13);

			var label14 = new Label();
			label14.Text = "Speed:";
			Grid.SetRow(label14, 4);

			_sliderSpeed = new HorizontalSlider();
			_sliderSpeed.Minimum = 0.1f;
			_sliderSpeed.Maximum = 3;
			_sliderSpeed.Value = 1;
			_sliderSpeed.Id = "_sliderSpeed";
			StackPanel.SetProportionType(_sliderSpeed, Myra.Graphics2D.UI.ProportionType.Fill);

			_labelSpeed = new Label();
			_labelSpeed.Text = "1.0";
			_labelSpeed.Width = 40;
			_labelSpeed.Id = "_labelSpeed";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			Grid.SetColumn(horizontalStackPanel1, 1);
			Grid.SetRow(horizontalStackPanel1, 4);
			horizontalStackPanel1.Widgets.Add(_sliderSpeed);
			horizontalStackPanel1.Widgets.Add(_labelSpeed);

			var grid1 = new Grid();
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 300,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.Widgets.Add(label1);
			grid1.Widgets.Add(_textPath);
			grid1.Widgets.Add(_buttonChangeTexture);
			grid1.Widgets.Add(_buttonClearTexture);
			grid1.Widgets.Add(label4);
			grid1.Widgets.Add(_imageColor);
			grid1.Widgets.Add(_buttonChangeColor);
			grid1.Widgets.Add(_buttonClearColor);
			grid1.Widgets.Add(label7);
			grid1.Widgets.Add(_comboAnimations);
			grid1.Widgets.Add(label11);
			grid1.Widgets.Add(_comboPlaybackMode);
			grid1.Widgets.Add(label14);
			grid1.Widgets.Add(horizontalStackPanel1);

			var label15 = new Label();
			label15.Text = "Crossfade";

			_checkCrossfade = new CheckButton();
			_checkCrossfade.IsChecked = true;
			_checkCrossfade.CheckContentSpacing = 8;
			_checkCrossfade.Id = "_checkCrossfade";
			_checkCrossfade.Content = label15;

			var label16 = new Label();
			label16.Text = "Play";

			_buttonPlayStop = new Button();
			_buttonPlayStop.Width = 100;
			_buttonPlayStop.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_buttonPlayStop.Id = "_buttonPlayStop";
			_buttonPlayStop.Content = label16;

			_sliderTime = new HorizontalSlider();
			_sliderTime.Width = 300;
			_sliderTime.Id = "_sliderTime";

			_labelTime = new Label();
			_labelTime.Text = "0.0";
			_labelTime.Id = "_labelTime";

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Spacing = 8;
			horizontalStackPanel2.Widgets.Add(_buttonPlayStop);
			horizontalStackPanel2.Widgets.Add(_sliderTime);
			horizontalStackPanel2.Widgets.Add(_labelTime);

			var label17 = new Label();
			label17.Text = "Draw Bounding Boxes";

			_checkDrawBoundingBoxes = new CheckButton();
			_checkDrawBoundingBoxes.CheckContentSpacing = 8;
			_checkDrawBoundingBoxes.Id = "_checkDrawBoundingBoxes";
			_checkDrawBoundingBoxes.Content = label17;

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(grid1);
			verticalStackPanel1.Widgets.Add(_checkCrossfade);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel2);
			verticalStackPanel1.Widgets.Add(_checkDrawBoundingBoxes);

			_labelFPS = new Label();
			_labelFPS.Text = "FPS:";
			_labelFPS.Left = -4;
			_labelFPS.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			_labelFPS.Id = "_labelFPS";

			var label18 = new Label();
			label18.Text = "Effects Switches:";

			var label19 = new Label();
			label19.Text = "Draw Calls:";
			Grid.SetRow(label19, 1);

			var label20 = new Label();
			label20.Text = "Vertices Drawn:";
			Grid.SetRow(label20, 2);

			var label21 = new Label();
			label21.Text = "Primitives Drawn:";
			Grid.SetRow(label21, 3);

			var label22 = new Label();
			label22.Text = "Meshes Drawn:";
			Grid.SetRow(label22, 4);

			_labelEffectsSwitches = new Label();
			_labelEffectsSwitches.Text = "10";
			_labelEffectsSwitches.Id = "_labelEffectsSwitches";
			Grid.SetColumn(_labelEffectsSwitches, 1);

			_labelDrawCalls = new Label();
			_labelDrawCalls.Text = "10";
			_labelDrawCalls.Id = "_labelDrawCalls";
			Grid.SetColumn(_labelDrawCalls, 1);
			Grid.SetRow(_labelDrawCalls, 1);

			_labelVerticesDrawn = new Label();
			_labelVerticesDrawn.Text = "10";
			_labelVerticesDrawn.Id = "_labelVerticesDrawn";
			Grid.SetColumn(_labelVerticesDrawn, 1);
			Grid.SetRow(_labelVerticesDrawn, 2);

			_labelPrimitivesDrawn = new Label();
			_labelPrimitivesDrawn.Text = "10";
			_labelPrimitivesDrawn.Id = "_labelPrimitivesDrawn";
			Grid.SetColumn(_labelPrimitivesDrawn, 1);
			Grid.SetRow(_labelPrimitivesDrawn, 3);

			_labelMeshesDrawn = new Label();
			_labelMeshesDrawn.Text = "10";
			_labelMeshesDrawn.Id = "_labelMeshesDrawn";
			Grid.SetColumn(_labelMeshesDrawn, 1);
			Grid.SetRow(_labelMeshesDrawn, 4);

			_panelStatistics = new Grid();
			_panelStatistics.ColumnSpacing = 8;
			_panelStatistics.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			_panelStatistics.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			_panelStatistics.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			_panelStatistics.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			_panelStatistics.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			_panelStatistics.Left = -4;
			_panelStatistics.Id = "_panelStatistics";
			_panelStatistics.Widgets.Add(label18);
			_panelStatistics.Widgets.Add(label19);
			_panelStatistics.Widgets.Add(label20);
			_panelStatistics.Widgets.Add(label21);
			_panelStatistics.Widgets.Add(label22);
			_panelStatistics.Widgets.Add(_labelEffectsSwitches);
			_panelStatistics.Widgets.Add(_labelDrawCalls);
			_panelStatistics.Widgets.Add(_labelVerticesDrawn);
			_panelStatistics.Widgets.Add(_labelPrimitivesDrawn);
			_panelStatistics.Widgets.Add(_labelMeshesDrawn);

			
			Widgets.Add(verticalStackPanel1);
			Widgets.Add(_labelFPS);
			Widgets.Add(_panelStatistics);
		}

		
		public TextBox _textPath;
		public Button _buttonChangeTexture;
		public Button _buttonClearTexture;
		public Image _imageColor;
		public Button _buttonChangeColor;
		public Button _buttonClearColor;
		public ComboView _comboAnimations;
		public ComboView _comboPlaybackMode;
		public HorizontalSlider _sliderSpeed;
		public Label _labelSpeed;
		public CheckButton _checkCrossfade;
		public Button _buttonPlayStop;
		public HorizontalSlider _sliderTime;
		public Label _labelTime;
		public CheckButton _checkDrawBoundingBoxes;
		public Label _labelFPS;
		public Label _labelEffectsSwitches;
		public Label _labelDrawCalls;
		public Label _labelVerticesDrawn;
		public Label _labelPrimitivesDrawn;
		public Label _labelMeshesDrawn;
		public Grid _panelStatistics;
	}
}
