/* Generated by MyraPad at 5/16/2026 5:08:22 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace DigitalRiseModel.Samples.Character.UI
{
	partial class MainPanel: Panel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "WASD - Move";

			var label2 = new Label();
			label2.Text = "Space - Jump";

			var label3 = new Label();
			label3.Text = "R - Draw/Sheath Weapon";

			var label4 = new Label();
			label4.Text = "Left Shift - Slash Weapon";

			var label5 = new Label();
			label5.Text = "Escape - Turn Mouse Lock On/Off";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Widgets.Add(label1);
			verticalStackPanel1.Widgets.Add(label2);
			verticalStackPanel1.Widgets.Add(label3);
			verticalStackPanel1.Widgets.Add(label4);
			verticalStackPanel1.Widgets.Add(label5);

			_labelFPS = new Label();
			_labelFPS.Text = "FPS:";
			_labelFPS.Left = -4;
			_labelFPS.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			_labelFPS.Id = "_labelFPS";

			var label6 = new Label();
			label6.Text = "Effects Switches:";

			var label7 = new Label();
			label7.Text = "Draw Calls:";
			Grid.SetRow(label7, 1);

			var label8 = new Label();
			label8.Text = "Vertices Drawn:";
			Grid.SetRow(label8, 2);

			var label9 = new Label();
			label9.Text = "Primitives Drawn:";
			Grid.SetRow(label9, 3);

			var label10 = new Label();
			label10.Text = "Meshes Drawn:";
			Grid.SetRow(label10, 4);

			_labelEffectsSwitches = new Label();
			_labelEffectsSwitches.Text = "10";
			_labelEffectsSwitches.Id = "_labelEffectsSwitches";
			Grid.SetColumn(_labelEffectsSwitches, 1);

			_labelDrawCalls = new Label();
			_labelDrawCalls.Text = "10";
			_labelDrawCalls.Id = "_labelDrawCalls";
			Grid.SetColumn(_labelDrawCalls, 1);
			Grid.SetRow(_labelDrawCalls, 1);

			_labelVerticesDrawn = new Label();
			_labelVerticesDrawn.Text = "10";
			_labelVerticesDrawn.Id = "_labelVerticesDrawn";
			Grid.SetColumn(_labelVerticesDrawn, 1);
			Grid.SetRow(_labelVerticesDrawn, 2);

			_labelPrimitivesDrawn = new Label();
			_labelPrimitivesDrawn.Text = "10";
			_labelPrimitivesDrawn.Id = "_labelPrimitivesDrawn";
			Grid.SetColumn(_labelPrimitivesDrawn, 1);
			Grid.SetRow(_labelPrimitivesDrawn, 3);

			_labelMeshesDrawn = new Label();
			_labelMeshesDrawn.Text = "10";
			_labelMeshesDrawn.Id = "_labelMeshesDrawn";
			Grid.SetColumn(_labelMeshesDrawn, 1);
			Grid.SetRow(_labelMeshesDrawn, 4);

			_panelStatistics = new Grid();
			_panelStatistics.ColumnSpacing = 8;
			_panelStatistics.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			
			_panelStatistics.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});_panelStatistics.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			_panelStatistics.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			_panelStatistics.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			_panelStatistics.Left = -4;
			_panelStatistics.Id = "_panelStatistics";
			_panelStatistics.Widgets.Add(label6);
			_panelStatistics.Widgets.Add(label7);
			_panelStatistics.Widgets.Add(label8);
			_panelStatistics.Widgets.Add(label9);
			_panelStatistics.Widgets.Add(label10);
			_panelStatistics.Widgets.Add(_labelEffectsSwitches);
			_panelStatistics.Widgets.Add(_labelDrawCalls);
			_panelStatistics.Widgets.Add(_labelVerticesDrawn);
			_panelStatistics.Widgets.Add(_labelPrimitivesDrawn);
			_panelStatistics.Widgets.Add(_labelMeshesDrawn);

			
			Widgets.Add(verticalStackPanel1);
			Widgets.Add(_labelFPS);
			Widgets.Add(_panelStatistics);
		}

		
		public Label _labelFPS;
		public Label _labelEffectsSwitches;
		public Label _labelDrawCalls;
		public Label _labelVerticesDrawn;
		public Label _labelPrimitivesDrawn;
		public Label _labelMeshesDrawn;
		public Grid _panelStatistics;
	}
}
