/* Generated by MyraPad at 9/19/2025 8:41:57 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace NursiaModel.Samples.ThirdPerson.UI
{
	partial class MainPanel: Panel
	{
		private void BuildUI()
		{
			_labelFPS = new Label();
			_labelFPS.Text = "FPS:";
			_labelFPS.Left = -4;
			_labelFPS.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			_labelFPS.Id = "_labelFPS";

			var label1 = new Label();
			label1.Text = "Effects Switches:";

			var label2 = new Label();
			label2.Text = "Draw Calls:";
			Grid.SetRow(label2, 1);

			var label3 = new Label();
			label3.Text = "Vertices Drawn:";
			Grid.SetRow(label3, 2);

			var label4 = new Label();
			label4.Text = "Primitives Drawn:";
			Grid.SetRow(label4, 3);

			var label5 = new Label();
			label5.Text = "Meshes Drawn:";
			Grid.SetRow(label5, 4);

			_labelEffectsSwitches = new Label();
			_labelEffectsSwitches.Text = "10";
			_labelEffectsSwitches.Id = "_labelEffectsSwitches";
			Grid.SetColumn(_labelEffectsSwitches, 1);

			_labelDrawCalls = new Label();
			_labelDrawCalls.Text = "10";
			_labelDrawCalls.Id = "_labelDrawCalls";
			Grid.SetColumn(_labelDrawCalls, 1);
			Grid.SetRow(_labelDrawCalls, 1);

			_labelVerticesDrawn = new Label();
			_labelVerticesDrawn.Text = "10";
			_labelVerticesDrawn.Id = "_labelVerticesDrawn";
			Grid.SetColumn(_labelVerticesDrawn, 1);
			Grid.SetRow(_labelVerticesDrawn, 2);

			_labelPrimitivesDrawn = new Label();
			_labelPrimitivesDrawn.Text = "10";
			_labelPrimitivesDrawn.Id = "_labelPrimitivesDrawn";
			Grid.SetColumn(_labelPrimitivesDrawn, 1);
			Grid.SetRow(_labelPrimitivesDrawn, 3);

			_labelMeshesDrawn = new Label();
			_labelMeshesDrawn.Text = "10";
			_labelMeshesDrawn.Id = "_labelMeshesDrawn";
			Grid.SetColumn(_labelMeshesDrawn, 1);
			Grid.SetRow(_labelMeshesDrawn, 4);

			_panelStatistics = new Grid();
			_panelStatistics.ColumnSpacing = 8;
			_panelStatistics.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			_panelStatistics.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			_panelStatistics.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			_panelStatistics.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			_panelStatistics.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			_panelStatistics.Left = -4;
			_panelStatistics.Id = "_panelStatistics";
			_panelStatistics.Widgets.Add(label1);
			_panelStatistics.Widgets.Add(label2);
			_panelStatistics.Widgets.Add(label3);
			_panelStatistics.Widgets.Add(label4);
			_panelStatistics.Widgets.Add(label5);
			_panelStatistics.Widgets.Add(_labelEffectsSwitches);
			_panelStatistics.Widgets.Add(_labelDrawCalls);
			_panelStatistics.Widgets.Add(_labelVerticesDrawn);
			_panelStatistics.Widgets.Add(_labelPrimitivesDrawn);
			_panelStatistics.Widgets.Add(_labelMeshesDrawn);

			
			Widgets.Add(_labelFPS);
			Widgets.Add(_panelStatistics);
		}

		
		public Label _labelFPS;
		public Label _labelEffectsSwitches;
		public Label _labelDrawCalls;
		public Label _labelVerticesDrawn;
		public Label _labelPrimitivesDrawn;
		public Label _labelMeshesDrawn;
		public Grid _panelStatistics;
	}
}
